plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pcmode.launcher'
    compileSdk 33

    defaultConfig {
        applicationId "com.pcmode.launcher"
        minSdk 23
        targetSdk 33
        versionCode 3
        versionName "3.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
